### ISSUE TITLE
DD35 Creation Step Order

### ISSUE THREAD

**Issue by tomizechsterson** [tomizechsterson/chargen-ui#79]
This is simply to make the issue order 100% clear, so it doesn't get forgotten:

- [x] #75 - Rolling Stats
- [x] #76 - Race/Class Selection
- [x] #77 - Stat Assignment
- [x] #81 - Racial Stat Adjustments
- [x] #80 - Ability Score Adjustments
- [x] #82 - Starting HP
- [x] #83 - Starting Attack Bonuses
- [x] #84 - Starting Saving Throws

**Comment by tomizechsterson** [comment]
This is starting to look redundant now that the milestone has been setup, and it can have its attached issues reordered. Closing this to try using the milestone instead
